namespace LenovoLegionToolkit.Lib.Features;

public class TouchpadLockFeature(PrecisionTouchpadLockFeature precisionTouchpadLockFeature, TouchpadLockWmiFeature touchpadLockWmiFeature)
    : AbstractCompositeFeature<TouchpadLockState>(precisionTouchpadLockFeature, touchpadLockWmiFeature);
